MODEL:
  NAME: 'resnet50'
  BACKBONE_EMB_SIZE: 2048
  PRETRAIN_PATH: './models/resnet50-19c8e357.pth'
  KEEP_CAMID_CENTROIDS: True

INPUT:
  SIZE_TRAIN: [256,128]
  SIZE_TEST: [256,128]

DATALOADER:
  NUM_INSTANCE: 4

SOLVER:
  BASE_LR: 0.0001
  OPTIMIZER_NAME: "Adam"
  MAX_EPOCHS: 120
  EVAL_PERIOD: 40

USE_MIXED_PRECISION: True

REPRODUCIBLE_NUM_RUNS: 3